# Generated by Django 3.2.4 on 2021-12-25 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('article_slug', models.CharField(max_length=50)),
                ('article_meta', models.CharField(max_length=200)),
                ('bcontent', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
