# Generated by Django 3.2.4 on 2021-12-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Blog',
        ),
    ]
