# Generated by Django 3.2.4 on 2021-12-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_article_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='islamicarticle',
        ),
    ]
