# Generated by Django 3.2.4 on 2021-12-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_blog_islamicarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicarticle',
            name='article_meta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='islamicarticle',
            name='bcontent',
            field=models.TextField(max_length=2000),
        ),
    ]
