# Generated by Django 3.2.4 on 2021-12-31 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20211230_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicarticle',
            name='article_slug',
            field=models.CharField(max_length=100),
        ),
    ]
