# Generated by Django 3.2.4 on 2022-01-03 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_islamicarticle_article_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('user_ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('Last_Name', models.CharField(max_length=100)),
                ('Email', models.TextField(max_length=100)),
                ('Phone', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
