# Generated by Django 3.2.4 on 2022-01-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
