# Generated by Django 3.2.4 on 2022-01-04 10:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0009_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hadith',
            fields=[
                ('Hadith_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ArabicText', models.CharField(max_length=2500)),
                ('HAdith_Trans', models.CharField(max_length=1000)),
                ('Hadith_Topic', models.CharField(max_length=300)),
                ('Hadith_referenece', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productID', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=200)),
                ('productQuantity', models.IntegerField()),
                ('productPrice', models.IntegerField()),
                ('InStock', models.BooleanField()),
                ('ImagePath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('questionID', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=250)),
                ('op1', models.CharField(max_length=200)),
                ('op2', models.CharField(max_length=200)),
                ('op3', models.CharField(max_length=200)),
                ('op4', models.CharField(max_length=200)),
                ('correctop', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuranicVerse',
            fields=[
                ('QuranicVerse_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ArabicText', models.CharField(max_length=2500)),
                ('Quranic_Trans', models.CharField(max_length=1000)),
                ('Quranic_Topic', models.CharField(max_length=300)),
                ('Quranic_reference', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('TransactionID', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('priceOneUnit', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.products')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
