# Generated by Django 3.2.4 on 2022-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_hadith_products_purchasehistory_quiz_quranicverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='islamicarticle',
            name='bcontent',
            field=models.TextField(max_length=5000),
        ),
    ]
