# Generated by Django 3.2.4 on 2022-01-31 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_productdetails_purchasinghistory_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='purchasehistory',
            name='username',
        ),
        migrations.RemoveField(
            model_name='purchasinghistory',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='purchasinghistory',
            name='username',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.DeleteModel(
            name='productDetails',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
        migrations.DeleteModel(
            name='PurchaseHistory',
        ),
        migrations.DeleteModel(
            name='purchasingHistory',
        ),
    ]
