# Generated by Django 3.2.4 on 2022-01-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20220131_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
    ]
