# Generated by Django 3.2.9 on 2022-01-20 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='last_Name',
            new_name='lastName',
        ),
    ]
