# Generated by Django 3.2.9 on 2022-01-22 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0002_rename_last_name_userdata_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasinghistory',
            name='priceOfOneUnit',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
