# Generated by Django 3.2.9 on 2022-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0004_alter_productdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
