# Generated by Django 3.2.9 on 2022-01-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0005_alter_productdetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasinghistory',
            name='productId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasinghistory',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
