# Generated by Django 3.2.9 on 2022-01-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('islamoshop', '0006_auto_20220123_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasinghistory',
            name='transactionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
